# Fruit Classification using CNN


If you changed something in your drive after you did the drive.mount('/content/drive'), you have to remount it with drive.mount('/content/drive', force_remount=True). force_remount is used only when you have to mount the drive irrespective of whether its loaded previously.

In [ ]:
!pip install tensorflowjs

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
!unzip "/content/drive/My Drive/fruits.zip"

In [ ]:
import cv2
import numpy as np
import os
import tensorflowjs as tfjs

In [ ]:
trainingDataset = []
classNumber = 0
img_size = 100
path = "/content/drive/My Drive/fruitsData/Training"

The clear() method removes all items from the list.

In [ ]:
trainingDataset.clear()
for folder in (os.listdir(path)):
  print(classNumber)
  fp = os.path.join(path,folder)
  for eachImage in os.listdir(fp):
    imagePath = os.path.join(fp,eachImage)
    img = (cv2.imread(imagePath,cv2.IMREAD_GRAYSCALE))/255
    trainingDataset.append([img,classNumber])
  classNumber = classNumber + 1

print(len(trainingDataset))
print(len(trainingDataset[0]))
print(trainingDataset[0])

Module 'time' is used to handle time-related tasks.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.utils import to_categorical
import pickle
import time

In [ ]:
X = []
Y = []
img_size = 100
np.random.shuffle(trainingDataset)
for features, label in trainingDataset:
    X.append(features)
    Y.append(label)
print(Y)    

[0, 2, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 2, 1, 2, 0, 1, 0, 1, 1, 1, 2, 2, 1, 0, 2, 2, 0, 0, 1, 2, 2, 1, 0, 1, 0, 0, 2, 0, 1, 0, 2, 0, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 0, 2, 2, 1, 2, 0, 0, 2, 1, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2, 1, 0, 2, 0, 1, 2, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 2, 0, 2, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 1, 2, 2, 2, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 2, 1, 2, 1, 2, 0, 0, 2, 0, 0, 2, 1, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2, 2, 2, 0, 0, 0, 1, 2, 1, 2, 0, 2, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 0, 2, 1, 2, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 2, 1, 2, 0, 1, 0, 2, 1, 0, 1, 2, 0, 1, 2, 2, 1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0, 2, 0, 2, 0, 1, 1, 2, 1, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 2, 2, 1, 0, 2, 1, 2, 2, 0, 0, 0, 

In [ ]:
X = np.array(X).reshape(-1, img_size, img_size, 1)
Y_binary = to_categorical(Y)
print(Y_binary)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


**Overfitting:** Good performance on the training data, poor generliazation to other data. <br>
**Underfitting:** Poor performance on the training data and poor generalization to other data.

**Dropout** is a technique where randomly selected neurons are ignored during training. They are “dropped-out” randomly. This means that their contribution to the activation of downstream neurons is temporally removed on the forward pass and any weight updates are not applied to the neuron on the backward pass.<br>
(Dropout(0.3) means setting 30% inputs to zero.

In [ ]:
model = Sequential()

model.add(Conv2D(40, (3, 3), input_shape=(100,100,1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.3))

model.add(Conv2D(60, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.3))

model.add(Conv2D(80, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.3))

model.add(Flatten())

model.add(Dense(100))
model.add(Activation('relu'))
 
model.add(Dense(3))
model.add(Activation('softmax'))

TensorBoard is a tool/dashboard for providing the measurements and visualizations needed during the machine learning workflow.

In [ ]:
# NAME = "3-conv-128-layer-dense-1-out-2-softmax-categorical-cross-2-CNN"
# tensorboard = TensorBoard(log_dir="/content/drive/My Drive/fruitsData/Logs/{}".format(NAME))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )

---- batch_size = 32 <br>
---- validation_split = 0.3

In [ ]:
model.fit(X, Y_binary,
          batch_size = 32,
          epochs=10, validation_split = 0.3)
 
model.save("/content/fruits-360_dataset/fruits-360/Models/{NAME}.model")

Epoch 1/10
33/33 [==============================] - 18s 516ms/step - loss: 0.4219 - accuracy: 0.8388 - val_loss: 0.0245 - val_accuracy: 0.9977
Epoch 2/10
33/33 [==============================] - 17s 509ms/step - loss: 0.0296 - accuracy: 0.9883 - val_loss: 0.0311 - val_accuracy: 0.9955
Epoch 3/10
33/33 [==============================] - 17s 512ms/step - loss: 0.0286 - accuracy: 0.9854 - val_loss: 0.0244 - val_accuracy: 1.0000
Epoch 4/10
33/33 [==============================] - 17s 507ms/step - loss: 0.0019 - accuracy: 1.0000 - val_loss: 0.0018 - val_accuracy: 1.0000
Epoch 5/10
33/33 [==============================] - 17s 506ms/step - loss: 4.8023e-04 - accuracy: 1.0000 - val_loss: 9.3560e-04 - val_accuracy: 1.0000
Epoch 6/10
33/33 [==============================] - 17s 505ms/step - loss: 5.1631e-04 - accuracy: 1.0000 - val_loss: 6.3623e-04 - val_accuracy: 1.0000
Epoch 7/10
33/33 [==============================] - 17s 513ms/step - loss: 0.0029 - accuracy: 0.9981 - val_loss: 0.0043 - val_

prepare() function prepares a test image according to the NN architecture

In [ ]:
def prepare(filepath):
    img_size = 100 
    img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)/255  
    img_resize = cv2.resize(img, (img_size, img_size))  
    return img_resize.reshape(-1, img_size, img_size, 1)

The numpy.argmax() function returns index of the max element of the array

In [ ]:
prediction = model.predict(prepare("/content/drive/My Drive/fruitsData/Test/Cocos/6_100.jpg"))
print((prediction))

CATEGORIES = ["Apple Braeburn", "Banana", "Cocos"]

pred_class = CATEGORIES[np.argmax(prediction)]
print(pred_class)



[[1.6759678e-06 2.8162238e-11 9.9999833e-01]]
Cocos
